version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - '8080:80'
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: server
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: nodemon index.js
    networks:
      - nodenet
    volumes:
      - ./server:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: arm64v8/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
